#!/usr/bin/env sh
#
# Copyright (C) Infocom LLC
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is part of Piano.
#
# Piano is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Piano is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General
# Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with Piano. If not, see <https://www.gnu.org/licenses/>.

wildmidi ${1} >/dev/null 2> /dev/null &
pid=$! >/dev/null 2> /dev/null &
sleep ${2}s >/dev/null 2> /dev/null &
kill -9 $pid >/dev/null 2> /dev/null &
